name: Build Project

on:
  push:
    branches:
      - main
      - dev
      - dev-table

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build
      env: 
        NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
        Bundle: True
      run: |
        dotnet restore src/BootstrapBlazor --no-cache
        dotnet build src/BootstrapBlazor

    - name: Test
      run: |
        dotnet test test/UnitTest -c Release --collect:"XPlat Code Coverage" -r ./coverage
        #dotnet test test/UnitTest.Localization -c Release -f net6.0 --collect:"XPlat Code Coverage" -r ./coverage

    - name: Upload to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/
